export const structureLayout:{
    [rcl: number]: {
        rcl: number,
        buildings: {
            [structureType: string]: { pos: Coord[] }
        }
    }
} = {
    1: {
        rcl:1,
        buildings:{
            extension:{pos:[]},
            spawn:{
                pos:[
                    {x:3,y:8}
                ]
            },
            road:{pos:[]},
            tower:{pos:[]},
            storage:{pos:[]},
            terminal:{pos:[]},
            powerSpawn:{pos:[]},
            link:{pos:[]},
            container:{pos:[]},
            lab:{pos:[]},
            nuker:{pos:[]},
            observer:{pos:[]},
            factory:{pos:[]}
        }
    },

    2: {
        rcl:2,
        buildings:{
            extension:{
                pos:[
                    {x:2,y:10},{x:3,y:10},{x:4,y:10},
                    {x:4,y:9},{x:4,y:8}
                ]
            },
            spawn:{
                pos:[
                    {x:3,y:8}
                ]
            },
            road:{pos:[]},
            tower:{pos:[]},
            storage:{pos:[]},
            terminal:{pos:[]},
            powerSpawn:{pos:[]},
            link:{pos:[]},
            container:{
                pos:[
                    {x:2,y:8},{x:5,y:6}
                ]
            },
            lab:{pos:[]},
            nuker:{pos:[]},
            observer:{pos:[]},
            factory:{pos:[]}
        }
    },

    3: {
        rcl:3,
        buildings:{
            extension:{
                pos:[
                    {x:0,y:9},{x:0,y:10},{x:1,y:10},
                    {x:2,y:10},{x:3,y:10},{x:4,y:10},
                    {x:4,y:9},{x:4,y:8},{x:2,y:9},
                    {x:1,y:8}
                ]
            },
            spawn:{
                pos:[
                    {x:3,y:8}
                ]
            },
            road:{
                pos:[
                    {x:0,y:5},{x:1,y:5},{x:2,y:5},{x:3,y:5},
                    {x:4,y:6},{x:4,y:7},{x:3,y:7},{x:2,y:8},
                    {x:5,y:8},{x:5,y:9},{x:5,y:10},{x:7,y:7},
                    {x:6,y:7},{x:6,y:6},{x:7,y:5},{x:5,y:5},
                    {x:8,y:5},{x:9,y:5},{x:10,y:5},{x:8,y:8},
                    {x:3,y:9},{x:1,y:9}
                ]
            },
            tower:{
                pos:[
                    {x:3,y:6}
                ]
            },
            storage:{pos:[]},
            terminal:{pos:[]},
            powerSpawn:{pos:[]},
            link:{pos:[]},
            container:{
                pos:[
                    {x:2,y:8},{x:5,y:6}
                ]
            },
            lab:{pos:[]},
            nuker:{pos:[]},
            observer:{pos:[]},
            factory:{pos:[]}
        }
    },

    4: {
        rcl:4,
        buildings:{
            extension:{
                pos:[
                    {x:0,y:6},{x:0,y:7},{x:0,y:8},
                    {x:0,y:9},{x:0,y:10},{x:1,y:10},
                    {x:2,y:10},{x:3,y:10},{x:4,y:10},
                    {x:4,y:9},{x:4,y:8},{x:1,y:6},
                    {x:2,y:6},{x:2,y:7},{x:2,y:9},
                    {x:1,y:8},{x:6,y:8},{x:6,y:9},
                    {x:6,y:10},{x:7,y:10}
                ]
            },
            spawn:{
                pos:[
                    {x:3,y:8}
                ]
            },
            road:{
                pos:[
                    {x:0,y:5},{x:1,y:5},{x:2,y:5},{x:3,y:5},
                    {x:4,y:6},{x:4,y:7},{x:3,y:7},{x:2,y:8},
                    {x:5,y:8},{x:5,y:9},{x:5,y:10},{x:8,y:8},
                    {x:7,y:7},{x:6,y:7},{x:6,y:6},{x:7,y:5},
                    {x:5,y:5},{x:6,y:4},{x:4,y:4},{x:4,y:3},
                    {x:8,y:5},{x:9,y:5},{x:10,y:5},{x:6,y:3},
                    {x:5,y:2},{x:5,y:1},{x:5,y:0},{x:9,y:9},
                    {x:9,y:7},{x:7,y:9},{x:3,y:9},{x:1,y:9},
                    {x:1,y:7}
                ]
            },
            tower:{
                pos:[
                    {x:3,y:6}
                ]
            },
            storage:{
                pos:[
                    {x:4,y:5}
                ]
            },
            terminal:{pos:[]},
            powerSpawn:{pos:[]},
            link:{pos:[]},
            container:{
                pos:[
                    {x:2,y:8},{x:8,y:8}
                ]
            },
            lab:{pos:[]},
            nuker:{pos:[]},
            observer:{pos:[]},
            factory:{pos:[]}
        }
    },

    5: {
        rcl:5,
        buildings:{
            extension:{
                pos:[
                    {x:0,y:6},{x:0,y:7},{x:0,y:8},
                    {x:0,y:9},{x:0,y:10},{x:1,y:10},
                    {x:2,y:10},{x:3,y:10},{x:4,y:10},
                    {x:4,y:9},{x:4,y:8},{x:1,y:6},
                    {x:2,y:6},{x:2,y:7},{x:2,y:9},
                    {x:1,y:8},{x:6,y:8},{x:6,y:9},
                    {x:6,y:10},{x:7,y:10},{x:8,y:10},
                    {x:9,y:10},{x:10,y:9},{x:10,y:10},
                    {x:10,y:8},{x:9,y:6},{x:8,y:6},
                    {x:8,y:7},{x:9,y:8},{x:8,y:9}
                ]
            },
            spawn:{
                pos:[
                    {x:3,y:8}
                ]
            },
            road:{
                pos:[
                    {x:0,y:5},{x:1,y:5},{x:2,y:5},{x:3,y:5},
                    {x:4,y:6},{x:4,y:7},{x:3,y:7},{x:2,y:8},
                    {x:5,y:8},{x:5,y:9},{x:5,y:10},{x:8,y:8},
                    {x:7,y:7},{x:6,y:7},{x:6,y:6},{x:7,y:5},
                    {x:5,y:5},{x:6,y:4},{x:4,y:4},{x:4,y:3},
                    {x:8,y:5},{x:9,y:5},{x:10,y:5},{x:6,y:3},
                    {x:5,y:2},{x:5,y:1},{x:5,y:0},{x:9,y:9},
                    {x:9,y:7},{x:7,y:9},{x:3,y:9},{x:1,y:9},
                    {x:1,y:7}
                ]
            },
            tower:{
                pos:[
                    {x:3,y:6},{x:7,y:6}
                ]
            },
            storage:{
                pos:[
                    {x:4,y:5}
                ]
            },
            terminal:{pos:[]},
            powerSpawn:{pos:[]},
            link:{
                pos:[
                    {x:5,y:6}
                ]
            },
            container:{
                pos:[
                    {x:2,y:8},{x:8,y:8}
                ]
            },
            lab:{pos:[]},
            nuker:{pos:[]},
            observer:{pos:[]},
            factory:{pos:[]}
        }
    },

    6: {
        rcl:6,
        buildings:{
            extension:{
                pos:[
                    {x:0,y:6},{x:0,y:7},{x:0,y:8},
                    {x:0,y:9},{x:0,y:10},{x:1,y:10},
                    {x:2,y:10},{x:3,y:10},{x:4,y:10},
                    {x:4,y:9},{x:4,y:8},{x:1,y:6},
                    {x:2,y:6},{x:2,y:7},{x:2,y:9},
                    {x:1,y:8},{x:6,y:8},{x:6,y:9},
                    {x:6,y:10},{x:7,y:10},{x:8,y:10},
                    {x:9,y:10},{x:10,y:9},{x:10,y:10},
                    {x:10,y:8},{x:10,y:7},{x:10,y:6},
                    {x:9,y:6},{x:8,y:6},{x:8,y:7},
                    {x:9,y:8},{x:8,y:9},{x:4,y:2},
                    {x:4,y:1},{x:4,y:0},{x:3,y:0},
                    {x:2,y:0},{x:2,y:1},{x:1,y:2},
                    {x:1,y:0}
                ]
            },
            spawn:{
                pos:[
                    {x:3,y:8}
                ]
            },
            road:{
                pos:[
                    {x:0,y:5},{x:1,y:5},{x:2,y:5},{x:3,y:5},
                    {x:4,y:6},{x:4,y:7},{x:3,y:7},{x:2,y:8},
                    {x:5,y:8},{x:5,y:9},{x:5,y:10},{x:8,y:8},
                    {x:7,y:7},{x:6,y:7},{x:6,y:6},{x:7,y:5},
                    {x:5,y:5},{x:6,y:4},{x:4,y:4},{x:4,y:3},
                    {x:3,y:3},{x:2,y:2},{x:5,y:2},{x:5,y:1},
                    {x:5,y:0},{x:8,y:5},{x:9,y:5},{x:10,y:5},
                    {x:6,y:3},{x:9,y:9},{x:9,y:7},{x:7,y:9},
                    {x:3,y:9},{x:1,y:9},{x:1,y:7},{x:1,y:3},
                    {x:1,y:1},{x:3,y:1},{x:7,y:3},{x:8,y:2},
                    {x:9,y:1},
                ]
            },
            tower:{
                pos:[
                    {x:3,y:6},{x:7,y:6}
                ]
            },
            storage:{
                pos:[
                    {x:4,y:5}
                ]
            },
            terminal:{
                pos:[
                    {x:6,y:5}
                ]
            },
            powerSpawn:{pos:[]},
            link:{
                pos:[
                    {x:5,y:6}
                ]
            },
            container:{
                pos:[
                    {x:2,y:8},{x:8,y:8},{x:2,y:2}
                ]
            },
            lab:{
                pos:[
                    {x:7,y:2},{x:8,y:3},{x:7,y:1},
                ]
            },
            nuker:{pos:[]},
            observer:{pos:[]},
            factory:{pos:[]}
        }
    },

    7: {
        rcl:7,
        buildings:{
            extension:{
                pos:[
                    {x:0,y:0},{x:1,y:0},{x:2,y:0},
                    {x:3,y:0},{x:4,y:0},{x:0,y:1},
                    {x:0,y:2},{x:0,y:3},{x:0,y:4},
                    {x:1,y:2},{x:2,y:1},{x:1,y:4},
                    {x:2,y:4},{x:2,y:3},{x:4,y:1},
                    {x:4,y:2},{x:0,y:6},{x:0,y:7},
                    {x:0,y:8},{x:0,y:9},{x:0,y:10},
                    {x:1,y:10},{x:2,y:10},{x:3,y:10},
                    {x:4,y:10},{x:4,y:9},{x:4,y:8},
                    {x:1,y:6},{x:2,y:6},{x:2,y:7},
                    {x:2,y:9},{x:1,y:8},{x:6,y:8},
                    {x:6,y:9},{x:6,y:10},{x:7,y:10},
                    {x:8,y:10},{x:9,y:10},{x:10,y:9},
                    {x:10,y:10},{x:10,y:8},{x:10,y:7},
                    {x:10,y:6},{x:9,y:6},{x:8,y:6},
                    {x:8,y:7},{x:9,y:8},{x:8,y:9}
                ]
            },
            spawn:{
                pos:[
                    {x:3,y:8},{x:7,y:8}
                ]
            },
            road:{
                pos:[
                    {x:0,y:5},{x:1,y:5},{x:2,y:5},{x:3,y:5},
                    {x:4,y:6},{x:4,y:7},{x:3,y:7},{x:2,y:8},
                    {x:5,y:8},{x:5,y:9},{x:5,y:10},{x:8,y:8},
                    {x:7,y:7},{x:6,y:7},{x:6,y:6},{x:7,y:5},
                    {x:5,y:5},{x:6,y:4},{x:4,y:4},{x:4,y:3},
                    {x:3,y:3},{x:2,y:2},{x:5,y:2},{x:5,y:1},
                    {x:5,y:0},{x:8,y:5},{x:9,y:5},{x:10,y:5},
                    {x:6,y:3},{x:9,y:9},{x:9,y:7},{x:7,y:9},
                    {x:3,y:9},{x:1,y:9},{x:1,y:7},{x:1,y:3},
                    {x:1,y:1},{x:3,y:1},{x:7,y:3},{x:8,y:2},
                    {x:9,y:1},
                ]
            },
            tower:{
                pos:[
                    {x:3,y:6},{x:5,y:7},{x:7,y:6}
                ]
            },
            storage:{
                pos:[
                    {x:4,y:5}
                ]
            },
            terminal:{
                pos:[
                    {x:6,y:5}
                ]
            },
            powerSpawn:{pos:[]},
            link:{
                pos:[
                    {x:5,y:6}
                ]
            },
            container:{
                pos:[
                    {x:2,y:8},{x:8,y:8},{x:2,y:2}
                ]
            },
            lab:{
                pos:[
                    {x:7,y:2},{x:8,y:3},{x:7,y:1},
                    {x:9,y:3},{x:8,y:1},{x:9,y:2},
                ]
            },
            nuker:{pos:[]},
            observer:{pos:[]},
            factory:{
                pos:[
                    {x:8,y:4}
                ]
            }
        }
    },

    8: {
        rcl:8,
        buildings:{
            extension:{
                pos:[
                    {x:0,y:0},{x:1,y:0},{x:2,y:0},
                    {x:3,y:0},{x:4,y:0},{x:0,y:1},
                    {x:0,y:2},{x:0,y:3},{x:0,y:4},
                    {x:1,y:2},{x:2,y:1},{x:1,y:4},
                    {x:2,y:4},{x:2,y:3},{x:4,y:1},
                    {x:4,y:2},{x:0,y:6},{x:0,y:7},
                    {x:0,y:8},{x:0,y:9},{x:0,y:10},
                    {x:1,y:10},{x:2,y:10},{x:3,y:10},
                    {x:4,y:10},{x:4,y:9},{x:4,y:8},
                    {x:1,y:6},{x:2,y:6},{x:2,y:7},
                    {x:2,y:9},{x:1,y:8},{x:6,y:8},
                    {x:6,y:9},{x:6,y:10},{x:7,y:10},
                    {x:8,y:10},{x:9,y:10},{x:10,y:9},
                    {x:10,y:10},{x:10,y:8},{x:10,y:7},
                    {x:10,y:6},{x:9,y:6},{x:8,y:6},
                    {x:8,y:7},{x:9,y:8},{x:8,y:9}
                ]
            },
            spawn:{
                pos:[
                    {x:3,y:8},{x:7,y:8},{x:3,y:2}
                ]
            },
            road:{
                pos:[
                    {x:0,y:5},{x:1,y:5},{x:2,y:5},{x:3,y:5},
                    {x:4,y:6},{x:4,y:7},{x:3,y:7},{x:2,y:8},
                    {x:5,y:8},{x:5,y:9},{x:5,y:10},{x:8,y:8},
                    {x:7,y:7},{x:6,y:7},{x:6,y:6},{x:7,y:5},
                    {x:5,y:5},{x:6,y:4},{x:4,y:4},{x:4,y:3},
                    {x:3,y:3},{x:2,y:2},{x:5,y:2},{x:5,y:1},
                    {x:5,y:0},{x:8,y:5},{x:9,y:5},{x:10,y:5},
                    {x:6,y:3},{x:9,y:9},{x:9,y:7},{x:7,y:9},
                    {x:3,y:9},{x:1,y:9},{x:1,y:7},{x:1,y:3},
                    {x:1,y:1},{x:3,y:1},{x:7,y:3},{x:8,y:2},
                    {x:9,y:1},{x:9,y:4},{x:9,y:4},{x:10,y:4},
                    {x:10,y:3},{x:6,y:1},{x:6,y:0},{x:7,y:0}
                ]
            },
            tower:{
                pos:[
                    {x:3,y:6},{x:3,y:4},{x:5,y:7},
                    {x:5,y:3},{x:7,y:6},{x:7,y:4}
                ]
            },
            storage:{
                pos:[
                    {x:4,y:5}
                ]
            },
            terminal:{
                pos:[
                    {x:6,y:5}
                ]
            },
            powerSpawn:{
                pos:[
                    {x:5,y:4}
                ]
            },
            link:{
                pos:[
                    {x:5,y:6}
                ]
            },
            container:{
                pos:[
                    {x:2,y:8},{x:8,y:8},{x:2,y:2}
                ]
            },
            lab:{
                pos:[
                    {x:7,y:2},{x:8,y:3},{x:7,y:1},
                    {x:9,y:3},{x:8,y:1},{x:9,y:2},
                    {x:8,y:0},{x:10,y:2},{x:9,y:0},
                    {x:10,y:1}
                ]
            },
            nuker:{
                pos:[
                    {x:6,y:2}
                ]
            },
            observer:{
                pos:[
                    {x:10,y:0}
                ]
            },
            factory:{
                pos:[
                    {x:8,y:4}
                ]
            }
        }
    }
}
